name: PythonVolumesProject
description: ''
version: v3.3
author: abhisheks+e2etests@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: pythonvolumesproject
  parentArtefactID: abhishekse2etestsprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-09-23 11:17:50'
pipelines:
  pipelines/p1:
    name: p1
    description: ''
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-09-23 11:17:50'
    datasets:
      inputs:
      - datasets/datasrte
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/p2:
    name: p2
    description: ''
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-09-23 11:23:02'
    datasets:
      inputs:
      - datasets/datasrte
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/p3:
    name: p3
    description: ''
    author: abhisheks+e2etests@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-09-23 12:36:11'
    datasets:
      inputs:
      - datasets/datasrte
      outputs: []
    subgraphs: []
    dependencies: {}
datasets:
  datasets/datasrte:
    name: datasrte
    description: ''
    author: abhisheks+e2etests@prophecy.io
    createdAt: '2024-09-23 11:25:25'
    mode: batch
    physicalDatasets:
      VolumesTestFabric:
        fabricId: 3574
        datasetType: File
        description: ''
        author: abhisheks+e2etests@prophecy.io
        createdAt: '2024-09-23 11:25:25'
templates: {}
jobs:
  jobs/job1:
    name: job1
    description: ''
    fabricUID: 3574
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/p1
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2024-09-23 11:19:36'
    author: abhisheks+e2etests@prophecy.io
    models: []
    sqlProjects: []
  jobs/job2:
    name: job2
    description: ''
    fabricUID: 3600
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/p2
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2024-09-23 11:32:09'
    author: abhisheks+e2etests@prophecy.io
    models: []
    sqlProjects: []
  jobs/job3:
    name: job3
    description: ''
    fabricUID: 3600
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/p3
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2024-09-23 12:36:28'
    author: abhisheks+e2etests@prophecy.io
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-09-23 11:17:50'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-09-23T11:17:50.663124Z'
  name: plibMaven
  version: 8.3.0-SNAPSHOT
  id: '82905882'
  createdAt: '2024-09-23T11:17:50.663124Z'
  type: plibMaven
- modifiedAt: '2024-09-23T11:17:50.663124Z'
  name: plibPypi
  version: 1.9.16
  id: '1987166085'
  createdAt: '2024-09-23T11:17:50.663124Z'
  type: plibPypi
projectDependencies:
  '42':
    projectUID: 42
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_42.git&subPath=
    version: 0.2.30.dev5
    isDefault: true
    author: null
    createdAt: '2024-09-23 11:17:39'
  '43':
    projectUID: 43
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/9gt3CHHz_team_9/pJIIcs5r_project_43.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-09-23 11:17:39'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
